steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/house_listings_frontend',
      '--build-arg=API_KEY=$_API_KEY',
      '--build-arg=MIDDLEWARE_ENDPOINT=_MIDDLEWARE_ENDPOINT',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'push',
            'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/house_listings_frontend',
    ]
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/house_listings_frontend'
timeout: 1200s
substitutions:
  _API_KEY: ''
  _MIDDLEWARE_ENDPOINT: ''
